name: Build app

on:
  push:

jobs:
  build-app:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Fastlane build
        run: fastlane build

      - name: Fastlane clean up
        run: fastlane clean_up